apiVersion: v1
kind: Service
metadata:
  name: qc-home-repo
  namespace: bit-2503
  labels:
    app: qc-home-repo
spec:
  selector:
    app: qc-home-repo
  type: ClusterIP
  ports:
    - name: http-com
      protocol: TCP
      port: 8087
      targetPort: 8087
    - name: http-home
      protocol: TCP
      port: 8088
      targetPort: 8088
    - name: http-quest
      protocol: TCP
      port: 8089
      targetPort: 8089
